In [5]:
import pandas as pd
import numpy as np

data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

Task 1: Load and Inspect the Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

In [ ]:
df.isna().sum()

transaction_id      0
date                0
region              3
product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

Task 2: Handle Missing Values
Region & Product_category: Fill with mode (most frequent value)

In [ ]:
df['region'] = df['region'].fillna(df['region'].mode()[0])
df['product_category'] = df['product_category'].fillna(df['product_category'].mode()[0])
df['region']

0     North
1     South
2      East
3      West
4     North
5     North
6     South
7     North
8      East
9      West
10    North
11    South
12     East
13     West
14    North
15    North
16     East
17     West
18    North
19    South
Name: region, dtype: object

In [ ]:
df['product_category']

0     Electronics
1        Clothing
2        Clothing
3           Books
4     Electronics
5            Home
6        Clothing
7           Books
8     Electronics
9        Clothing
10           Home
11       Clothing
12          Books
13    Electronics
14           Home
15       Clothing
16          Books
17    Electronics
18           Home
19       Clothing
Name: product_category, dtype: object

Sales_amount: Fill with median

In [ ]:
median_value = df['sales_amount'].median()
median_value
df['sales_amount'] = df['sales_amount'].fillna(median_value)
print(df['sales_amount'])
print("Missing values after filling:")
print(df['sales_amount'].isna().sum())

0     1200.0
1      450.0
2      890.0
3      725.0
4     1500.0
5      670.0
6      725.0
7      340.0
8     2100.0
9      780.0
10     560.0
11     725.0
12     420.0
13    1800.0
14     920.0
15     510.0
16     380.0
17     725.0
18    1100.0
19     640.0
Name: sales_amount, dtype: float64
Missing values after filling:
0

Quantity: Fill using forward fill (ffill)

In [ ]:
df['quantity'] = df['quantity'].fillna(method='ffill')
print(df['quantity'])
print(df['quantity'].isna().sum())

0     2.0
1     5.0
2     3.0
3     1.0
4     1.0
5     4.0
6     2.0
8     1.0
9     5.0
10    3.0
11    2.0
12    2.0
14    4.0
15    3.0
16    2.0
17    1.0
18    1.0
Name: quantity, dtype: float64
0

/tmp/ipykernel_1237/2145249789.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['quantity'] = df['quantity'].fillna(method='ffill')
/tmp/ipykernel_1237/2145249789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantity'] = df['quantity'].fillna(method='ffill')

Customer_age: Fill with mean (rounded to integer)

In [ ]:
age_mean = round(df['customer_age'].mean())
print(age_mean)
df['customer_age'] = df['customer_age'].fillna(mean_age)
print(df['customer_age'])
print(df['customer_age'].isna().sum())

37
0     25.0
1     34.0
2     37.0
3     45.0
4     29.0
5     37.0
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    37.0
12    48.0
13    26.0
14    35.0
15    42.0
16    37.0
17    31.0
18    39.0
19    44.0
Name: customer_age, dtype: float64
0

In [ ]:
df['payment_method'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19     True
Name: payment_method, dtype: bool

Payment_method: Drop rows where payment_method is missing

In [ ]:
df = df.dropna(subset=['payment_method'])
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

In [ ]:
print("Missing values in payment_method:")
print(df['payment_method'].isna().sum())

Missing values in payment_method:
0

In [ ]:
print("\nUpdated DataFrame shape:")
print(df.shape)

Updated DataFrame shape:
(17, 8)

Task 3: GroupBy Analysis
Calculate total sales by region

In [ ]:
region_sales = df.groupby('region')['sales_amount'].sum()

print(region_sales)

region
East     3790.0
North    4450.0
South    1090.0
West     2580.0
Name: sales_amount, dtype: float64

Calculate average sales by product_category

In [ ]:
category_avg_sales = df.groupby('product_category')['sales_amount'].mean()

print(category_avg_sales)

product_category
Books           380.000000
Clothing        533.333333
Electronics    1650.000000
Home            812.500000
Name: sales_amount, dtype: float64

Group by both region and product_category, calculate total sales and quantity, then use reset_index() to flatten

In [ ]:
grouped_df = df.groupby(['region', 'product_category']).agg({
    'sales_amount': 'sum',
    'quantity': 'sum'
}).reset_index()
print(grouped_df)

  region product_category  sales_amount  quantity
0   East            Books         800.0       2.0
1   East      Electronics        2100.0       1.0
2  North      Electronics        1200.0       2.0
3  North             Home        3250.0      11.0
4  South         Clothing        1090.0      13.0
5   West            Books           0.0       1.0
6   West      Electronics        1800.0       2.0

Display top 3 region-product combinations by sales

In [ ]:
top3 = grouped_df.sort_values(by='sales_amount', ascending=False).head(3)
top3

  region product_category  sales_amount  quantity
3  North             Home        3250.0      11.0
1   East      Electronics        2100.0       1.0
6   West      Electronics        1800.0       2.0

Task 4: Custom Aggregation: Create a function sales_range() that returns max - min of sales

In [6]:
def sales_range(series):
    return series.max() - series.min()

range_value = sales_range(df['sales_amount'])

print("Sales Range (Max - Min):", range_value)

Sales Range (Max - Min): 1760.0

Apply it to find sales range for each region

In [8]:
region_sales_range = df.groupby('region')['sales_amount'].apply(sales_range).reset_index()
region_sales_range

  region  sales_amount
0   East        1720.0
1  North         640.0
2  South         190.0
3   West        1020.0

Use .agg() to calculate multiple metrics by region:
sales_amount: sum, mean, max
quantity: sum, min

In [10]:
region_summary = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean', 'max'],
    'quantity': ['sum', 'min']
}).reset_index()

region_summary

  region sales_amount                 quantity
                  sum    mean     max      sum  min
0   East       3790.0   947.5  2100.0      6.0  1.0
1  North       4450.0   890.0  1200.0     13.0  2.0
2  South       1090.0   545.0   640.0     13.0  2.0
3   West       2580.0  1290.0  1800.0      8.0  1.0